title: cli - my tips and tricks
email: cli@pignat.org
description: >- # this means to ignore newlines until "baseurl:"
  Notebook for storing and sharing my opensource experience. Management
  of my servers and day to day laptop use.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cli.pignat.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RRandomReaper
github_username:  RandomReaper

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: jekyll-theme-basically-basic
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

tag_page_layout: tag_page
tag_page_dir: tag
