title: cli.pignat.org
#email: cli@pignat.org
description: >- # this means to ignore newlines until "baseurl:"
  my tips and tricks
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cli.pignat.org" # the base hostname & protocol for your site, e.g. http://example.com
author: RandomReaper
publisher: pignat.org
twitter_username: RRandomReaper
github_username:  RandomReaper
logo: /data/img/logo.svg
# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: jekyll-theme-basically-basic
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

tag_page_layout: tag_page
tag_page_dir: tag
