title: cli.pignat.org
#email: cli@pignat.org
description: >- # this means to ignore newlines until "baseurl:"
  my tips and tricks
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cli.pignat.org" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: RandomReaper
publisher: pignat.org
twitter_username: RRandomReaper
github_username:  RandomReaper
stackexchange_username: 2363064
logo: /data/img/logo.png
# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: jekyll-theme-basically-basic
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

tag_page_layout: tag_page
tag_page_dir: tag
ignored_tags: [xsuperseded,ximport]

defaults:
  - scope:
      path: ""
    values:
      image: /data/img/wide/site.jpg
